
CREATE DATABASE if NOT EXISTS thanx;
USE thanx;
DROP TABLE IF EXISTS users;

CREATE TABLE users
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT Users_Email UNIQUE (email),
  CONSTRAINT User_Name UNIQUE (username)
) AUTO_INCREMENT = 1;

DROP TABLE IF EXISTS reward_points;
CREATE TABLE reward_points
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  points_balance INT DEFAULT NULL,
  user_id BIGINT UNSIGNED,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

DROP TABLE IF EXISTS rewards;
CREATE TABLE rewards
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT NULL,
  description VARCHAR(255) DEFAULT NULL,
  points_required INT DEFAULT NULL,
  quantity_available INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) AUTO_INCREMENT = 1;

DROP TABLE IF EXISTS redemptions;
CREATE TABLE redemptions
(
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED,
  reward_id BIGINT UNSIGNED,
  redemption_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  points_spent INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (reward_id) REFERENCES rewards(id)
) AUTO_INCREMENT = 1;
