
CREATE DATABASE if NOT EXISTS thanx;
USE thanx;
DROP TABLE IF EXISTS users;

CREATE TABLE users
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT NULL,
  username VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT Users_Email UNIQUE (email),
  CONSTRAINT User_Name UNIQUE (username)
) AUTO_INCREMENT = 1;